apiVersion: apps/v1
kind: Deployment
metadata:
  name: monero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monero
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monero
    spec:
      containers:
      - args:
        - --non-interactive
        - --restricted-rpc
        - --rpc-bind-ip=0.0.0.0
        - --confirm-external-bind
        - --data-dir=/home/monero/.bitmonero
        image: tkeber/monerod-docker:v0.17.3.2
        imagePullPolicy: IfNotPresent
        name: monero
        volumeMounts:
        - mountPath: /home/monero/.bitmonero
          name: data
      nodeSelector:
        kubernetes.io/arch: arm
      securityContext:
        fsGroup: 1000
      tolerations:
      - key: class
        operator: Equal
        value: Gen2
        effect: NoSchedule
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: monero
